/*
 *    Copyright 2016 Nest Labs Inc. All Rights Reserved.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt -i cmdline.ggo 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "A command-line interface for the OpenThread driver.";

const char *gengetopt_args_info_usage = "Usage: thread-ctl [OPTIONS]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "  -V, --version                 Print version and exit",
  "  -I, --interface=STRING        Network Interface",
  "\nThread Options:",
  "      --key[=STRING]            Get/Set the Thread Master Key",
  "      --key-sequence[=INT]      Get/Set the Thread Key Sequence",
  "      --mode[=STRING]           Get/Set the Thread device mode\n                                  r: rx-on-when-idle\n                                  s: secure data request\n                                  d: full function device\n                                  n: full network data",
  "      --prefix[=STRING]         Get/Set the Thread Mesh Local Prefix",
  "      --state[=ENUM]            Get/Set the Thread state  (possible\n                                  values=\"detached\", \"child\", \"router\",\n                                  \"leader\", \"unspec\" default=`unspec')",
  "      --status[=ENUM]           Get/Set the Thread status  (possible\n                                  values=\"up\", \"down\", \"unspec\"\n                                  default=`unspec')",
  "      --timeout[=INT]           Get/Set the Thread timeout",
  "\nIEEE 802.15.4 Options:",
  "      --channel[=INT]           Get/Set the IEEE 802.15.4 Channel",
  "      --panid[=INT]             Get/Set the IEEE 802.15.4 PAN ID",
  "      --xpanid[=STRING]         Get/Set the IEEE 802.15.4 Extended PAN ID",
  "      --netname[=STRING]        Get/Set the IEEE 802.15.4 Network Name",
  "      --shortaddr               Get the IEEE 802.15.4 Short Address\n                                  (default=off)",
  "      --extaddr                 Get the IEEE 802.15.4 Extended Address\n                                  (default=off)",
  "      --whitelist-status[=ENUM] Get/Set the IEEE 802.15.4 whitelist status\n                                  (possible values=\"enable\", \"disable\",\n                                  \"unspec\" default=`unspec')",
  "      --whitelist-add=STRING    Add an IEEE 802.15.4 Extended Address to the\n                                  whitelist",
  "      --whitelist-delete=STRING Delete an IEEE 802.15.4 Extended Address from\n                                  the whitelist",
  "      --whitelist-show          Show the IEEE 802.15.4 Extended Addresses in\n                                  the whitelist  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_ENUM
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_state_values[] = {"detached", "child", "router", "leader", "unspec", 0}; /*< Possible values for state. */
const char *cmdline_parser_status_values[] = {"up", "down", "unspec", 0}; /*< Possible values for status. */
const char *cmdline_parser_whitelist_status_values[] = {"enable", "disable", "unspec", 0}; /*< Possible values for whitelist-status. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->interface_given = 0 ;
  args_info->key_given = 0 ;
  args_info->key_sequence_given = 0 ;
  args_info->mode_given = 0 ;
  args_info->prefix_given = 0 ;
  args_info->state_given = 0 ;
  args_info->status_given = 0 ;
  args_info->timeout_given = 0 ;
  args_info->channel_given = 0 ;
  args_info->panid_given = 0 ;
  args_info->xpanid_given = 0 ;
  args_info->netname_given = 0 ;
  args_info->shortaddr_given = 0 ;
  args_info->extaddr_given = 0 ;
  args_info->whitelist_status_given = 0 ;
  args_info->whitelist_add_given = 0 ;
  args_info->whitelist_delete_given = 0 ;
  args_info->whitelist_show_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->interface_arg = NULL;
  args_info->interface_orig = NULL;
  args_info->key_arg = NULL;
  args_info->key_orig = NULL;
  args_info->key_sequence_orig = NULL;
  args_info->mode_arg = NULL;
  args_info->mode_orig = NULL;
  args_info->prefix_arg = NULL;
  args_info->prefix_orig = NULL;
  args_info->state_arg = state_arg_unspec;
  args_info->state_orig = NULL;
  args_info->status_arg = status_arg_unspec;
  args_info->status_orig = NULL;
  args_info->timeout_orig = NULL;
  args_info->channel_orig = NULL;
  args_info->panid_orig = NULL;
  args_info->xpanid_arg = NULL;
  args_info->xpanid_orig = NULL;
  args_info->netname_arg = NULL;
  args_info->netname_orig = NULL;
  args_info->shortaddr_flag = 0;
  args_info->extaddr_flag = 0;
  args_info->whitelist_status_arg = whitelist_status_arg_unspec;
  args_info->whitelist_status_orig = NULL;
  args_info->whitelist_add_arg = NULL;
  args_info->whitelist_add_orig = NULL;
  args_info->whitelist_delete_arg = NULL;
  args_info->whitelist_delete_orig = NULL;
  args_info->whitelist_show_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->interface_help = gengetopt_args_info_help[2] ;
  args_info->key_help = gengetopt_args_info_help[4] ;
  args_info->key_sequence_help = gengetopt_args_info_help[5] ;
  args_info->mode_help = gengetopt_args_info_help[6] ;
  args_info->prefix_help = gengetopt_args_info_help[7] ;
  args_info->state_help = gengetopt_args_info_help[8] ;
  args_info->status_help = gengetopt_args_info_help[9] ;
  args_info->timeout_help = gengetopt_args_info_help[10] ;
  args_info->channel_help = gengetopt_args_info_help[12] ;
  args_info->panid_help = gengetopt_args_info_help[13] ;
  args_info->xpanid_help = gengetopt_args_info_help[14] ;
  args_info->netname_help = gengetopt_args_info_help[15] ;
  args_info->shortaddr_help = gengetopt_args_info_help[16] ;
  args_info->extaddr_help = gengetopt_args_info_help[17] ;
  args_info->whitelist_status_help = gengetopt_args_info_help[18] ;
  args_info->whitelist_add_help = gengetopt_args_info_help[19] ;
  args_info->whitelist_delete_help = gengetopt_args_info_help[20] ;
  args_info->whitelist_show_help = gengetopt_args_info_help[21] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->interface_arg));
  free_string_field (&(args_info->interface_orig));
  free_string_field (&(args_info->key_arg));
  free_string_field (&(args_info->key_orig));
  free_string_field (&(args_info->key_sequence_orig));
  free_string_field (&(args_info->mode_arg));
  free_string_field (&(args_info->mode_orig));
  free_string_field (&(args_info->prefix_arg));
  free_string_field (&(args_info->prefix_orig));
  free_string_field (&(args_info->state_orig));
  free_string_field (&(args_info->status_orig));
  free_string_field (&(args_info->timeout_orig));
  free_string_field (&(args_info->channel_orig));
  free_string_field (&(args_info->panid_orig));
  free_string_field (&(args_info->xpanid_arg));
  free_string_field (&(args_info->xpanid_orig));
  free_string_field (&(args_info->netname_arg));
  free_string_field (&(args_info->netname_orig));
  free_string_field (&(args_info->whitelist_status_orig));
  free_string_field (&(args_info->whitelist_add_arg));
  free_string_field (&(args_info->whitelist_add_orig));
  free_string_field (&(args_info->whitelist_delete_arg));
  free_string_field (&(args_info->whitelist_delete_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->interface_given)
    write_into_file(outfile, "interface", args_info->interface_orig, 0);
  if (args_info->key_given)
    write_into_file(outfile, "key", args_info->key_orig, 0);
  if (args_info->key_sequence_given)
    write_into_file(outfile, "key-sequence", args_info->key_sequence_orig, 0);
  if (args_info->mode_given)
    write_into_file(outfile, "mode", args_info->mode_orig, 0);
  if (args_info->prefix_given)
    write_into_file(outfile, "prefix", args_info->prefix_orig, 0);
  if (args_info->state_given)
    write_into_file(outfile, "state", args_info->state_orig, cmdline_parser_state_values);
  if (args_info->status_given)
    write_into_file(outfile, "status", args_info->status_orig, cmdline_parser_status_values);
  if (args_info->timeout_given)
    write_into_file(outfile, "timeout", args_info->timeout_orig, 0);
  if (args_info->channel_given)
    write_into_file(outfile, "channel", args_info->channel_orig, 0);
  if (args_info->panid_given)
    write_into_file(outfile, "panid", args_info->panid_orig, 0);
  if (args_info->xpanid_given)
    write_into_file(outfile, "xpanid", args_info->xpanid_orig, 0);
  if (args_info->netname_given)
    write_into_file(outfile, "netname", args_info->netname_orig, 0);
  if (args_info->shortaddr_given)
    write_into_file(outfile, "shortaddr", 0, 0 );
  if (args_info->extaddr_given)
    write_into_file(outfile, "extaddr", 0, 0 );
  if (args_info->whitelist_status_given)
    write_into_file(outfile, "whitelist-status", args_info->whitelist_status_orig, cmdline_parser_whitelist_status_values);
  if (args_info->whitelist_add_given)
    write_into_file(outfile, "whitelist-add", args_info->whitelist_add_orig, 0);
  if (args_info->whitelist_delete_given)
    write_into_file(outfile, "whitelist-delete", args_info->whitelist_delete_orig, 0);
  if (args_info->whitelist_show_given)
    write_into_file(outfile, "whitelist-show", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->interface_given)
    {
      fprintf (stderr, "%s: '--interface' ('-I') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "interface",	1, NULL, 'I' },
        { "key",	2, NULL, 0 },
        { "key-sequence",	2, NULL, 0 },
        { "mode",	2, NULL, 0 },
        { "prefix",	2, NULL, 0 },
        { "state",	2, NULL, 0 },
        { "status",	2, NULL, 0 },
        { "timeout",	2, NULL, 0 },
        { "channel",	2, NULL, 0 },
        { "panid",	2, NULL, 0 },
        { "xpanid",	2, NULL, 0 },
        { "netname",	2, NULL, 0 },
        { "shortaddr",	0, NULL, 0 },
        { "extaddr",	0, NULL, 0 },
        { "whitelist-status",	2, NULL, 0 },
        { "whitelist-add",	1, NULL, 0 },
        { "whitelist-delete",	1, NULL, 0 },
        { "whitelist-show",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVI:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'I':	/* Network Interface.  */
        
        
          if (update_arg( (void *)&(args_info->interface_arg), 
               &(args_info->interface_orig), &(args_info->interface_given),
              &(local_args_info.interface_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "interface", 'I',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Get/Set the Thread Master Key.  */
          if (strcmp (long_options[option_index].name, "key") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->key_arg), 
                 &(args_info->key_orig), &(args_info->key_given),
                &(local_args_info.key_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "key", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the Thread Key Sequence.  */
          else if (strcmp (long_options[option_index].name, "key-sequence") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->key_sequence_arg), 
                 &(args_info->key_sequence_orig), &(args_info->key_sequence_given),
                &(local_args_info.key_sequence_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "key-sequence", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the Thread device mode
          r: rx-on-when-idle
          s: secure data request
          d: full function device
          n: full network data.  */
          else if (strcmp (long_options[option_index].name, "mode") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->mode_arg), 
                 &(args_info->mode_orig), &(args_info->mode_given),
                &(local_args_info.mode_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "mode", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the Thread Mesh Local Prefix.  */
          else if (strcmp (long_options[option_index].name, "prefix") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->prefix_arg), 
                 &(args_info->prefix_orig), &(args_info->prefix_given),
                &(local_args_info.prefix_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "prefix", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the Thread state.  */
          else if (strcmp (long_options[option_index].name, "state") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->state_arg), 
                 &(args_info->state_orig), &(args_info->state_given),
                &(local_args_info.state_given), optarg, cmdline_parser_state_values, "unspec", ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "state", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the Thread status.  */
          else if (strcmp (long_options[option_index].name, "status") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->status_arg), 
                 &(args_info->status_orig), &(args_info->status_given),
                &(local_args_info.status_given), optarg, cmdline_parser_status_values, "unspec", ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "status", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the Thread timeout.  */
          else if (strcmp (long_options[option_index].name, "timeout") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->timeout_arg), 
                 &(args_info->timeout_orig), &(args_info->timeout_given),
                &(local_args_info.timeout_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "timeout", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the IEEE 802.15.4 Channel.  */
          else if (strcmp (long_options[option_index].name, "channel") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->channel_arg), 
                 &(args_info->channel_orig), &(args_info->channel_given),
                &(local_args_info.channel_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "channel", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the IEEE 802.15.4 PAN ID.  */
          else if (strcmp (long_options[option_index].name, "panid") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->panid_arg), 
                 &(args_info->panid_orig), &(args_info->panid_given),
                &(local_args_info.panid_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "panid", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the IEEE 802.15.4 Extended PAN ID.  */
          else if (strcmp (long_options[option_index].name, "xpanid") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->xpanid_arg), 
                 &(args_info->xpanid_orig), &(args_info->xpanid_given),
                &(local_args_info.xpanid_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "xpanid", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the IEEE 802.15.4 Network Name.  */
          else if (strcmp (long_options[option_index].name, "netname") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->netname_arg), 
                 &(args_info->netname_orig), &(args_info->netname_given),
                &(local_args_info.netname_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "netname", '-',
                additional_error))
              goto failure;
          
          }
          /* Get the IEEE 802.15.4 Short Address.  */
          else if (strcmp (long_options[option_index].name, "shortaddr") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->shortaddr_flag), 0, &(args_info->shortaddr_given),
                &(local_args_info.shortaddr_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "shortaddr", '-',
                additional_error))
              goto failure;
          
          }
          /* Get the IEEE 802.15.4 Extended Address.  */
          else if (strcmp (long_options[option_index].name, "extaddr") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->extaddr_flag), 0, &(args_info->extaddr_given),
                &(local_args_info.extaddr_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "extaddr", '-',
                additional_error))
              goto failure;
          
          }
          /* Get/Set the IEEE 802.15.4 whitelist status.  */
          else if (strcmp (long_options[option_index].name, "whitelist-status") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->whitelist_status_arg), 
                 &(args_info->whitelist_status_orig), &(args_info->whitelist_status_given),
                &(local_args_info.whitelist_status_given), optarg, cmdline_parser_whitelist_status_values, "unspec", ARG_ENUM,
                check_ambiguity, override, 0, 0,
                "whitelist-status", '-',
                additional_error))
              goto failure;
          
          }
          /* Add an IEEE 802.15.4 Extended Address to the whitelist.  */
          else if (strcmp (long_options[option_index].name, "whitelist-add") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->whitelist_add_arg), 
                 &(args_info->whitelist_add_orig), &(args_info->whitelist_add_given),
                &(local_args_info.whitelist_add_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "whitelist-add", '-',
                additional_error))
              goto failure;
          
          }
          /* Delete an IEEE 802.15.4 Extended Address from the whitelist.  */
          else if (strcmp (long_options[option_index].name, "whitelist-delete") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->whitelist_delete_arg), 
                 &(args_info->whitelist_delete_orig), &(args_info->whitelist_delete_given),
                &(local_args_info.whitelist_delete_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "whitelist-delete", '-',
                additional_error))
              goto failure;
          
          }
          /* Show the IEEE 802.15.4 Extended Addresses in the whitelist.  */
          else if (strcmp (long_options[option_index].name, "whitelist-show") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->whitelist_show_flag), 0, &(args_info->whitelist_show_given),
                &(local_args_info.whitelist_show_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "whitelist-show", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
