/*
 *    Copyright 2016 Nest Labs Inc. All Rights Reserved.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

/**
 * @file
 *   This file implements protobuf messages for the OpenThread stack.
 *
 * @note
 *   This file was generated by the protocol buffer compiler.
 */

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ncp.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ncp.pb-c.h"
void   thread_primitive__init
                     (ThreadPrimitive         *message)
{
  static ThreadPrimitive init_value = THREAD_PRIMITIVE__INIT;
  *message = init_value;
}
size_t thread_primitive__pack
                     (const ThreadPrimitive *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_primitive__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
ThreadPrimitive *
       thread_primitive__unpack
                     (size_t               len,
                      const uint8_t       *data,
                      ThreadPrimitive         *message)
{
  return (ThreadPrimitive *)
     protobuf_c_message_unpack (&thread_primitive__descriptor,
                                len, data, (ProtobufCMessage*)message);
}
void   thread_state__init
                     (ThreadState         *message)
{
  static ThreadState init_value = THREAD_STATE__INIT;
  *message = init_value;
}
size_t thread_state__pack
                     (const ThreadState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
ThreadState *
       thread_state__unpack
                     (size_t               len,
                      const uint8_t       *data,
                      ThreadState         *message)
{
  return (ThreadState *)
     protobuf_c_message_unpack (&thread_state__descriptor,
                                len, data, (ProtobufCMessage*)message);
}
void   thread_whitelist__init
                     (ThreadWhitelist         *message)
{
  static ThreadWhitelist init_value = THREAD_WHITELIST__INIT;
  *message = init_value;
}
size_t thread_whitelist__pack
                     (const ThreadWhitelist *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_whitelist__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
ThreadWhitelist *
       thread_whitelist__unpack
                     (size_t               len,
                      const uint8_t       *data,
                      ThreadWhitelist         *message)
{
  return (ThreadWhitelist *)
     protobuf_c_message_unpack (&thread_whitelist__descriptor,
                                len, data, (ProtobufCMessage*)message);
}
void   thread_ip6_addresses__init
                     (ThreadIp6Addresses         *message)
{
  static ThreadIp6Addresses init_value = THREAD_IP6_ADDRESSES__INIT;
  *message = init_value;
}
size_t thread_ip6_addresses__pack
                     (const ThreadIp6Addresses *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_ip6_addresses__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
ThreadIp6Addresses *
       thread_ip6_addresses__unpack
                     (size_t               len,
                      const uint8_t       *data,
                      ThreadIp6Addresses         *message)
{
  return (ThreadIp6Addresses *)
     protobuf_c_message_unpack (&thread_ip6_addresses__descriptor,
                                len, data, (ProtobufCMessage*)message);
}
void   thread_scan_request__init
                     (ThreadScanRequest         *message)
{
  static ThreadScanRequest init_value = THREAD_SCAN_REQUEST__INIT;
  *message = init_value;
}
size_t thread_scan_request__pack
                     (const ThreadScanRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_scan_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
ThreadScanRequest *
       thread_scan_request__unpack
                     (size_t               len,
                      const uint8_t       *data,
                      ThreadScanRequest         *message)
{
  return (ThreadScanRequest *)
     protobuf_c_message_unpack (&thread_scan_request__descriptor,
                                len, data, (ProtobufCMessage*)message);
}
void   thread_scan_result__init
                     (ThreadScanResult         *message)
{
  static ThreadScanResult init_value = THREAD_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t thread_scan_result__pack
                     (const ThreadScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
ThreadScanResult *
       thread_scan_result__unpack
                     (size_t               len,
                      const uint8_t       *data,
                      ThreadScanResult         *message)
{
  return (ThreadScanResult *)
     protobuf_c_message_unpack (&thread_scan_result__descriptor,
                                len, data, (ProtobufCMessage*)message);
}
void   thread_scan_result_done__init
                     (ThreadScanResultDone         *message)
{
  static ThreadScanResultDone init_value = THREAD_SCAN_RESULT_DONE__INIT;
  *message = init_value;
}
size_t thread_scan_result_done__pack
                     (const ThreadScanResultDone *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_scan_result_done__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
ThreadScanResultDone *
       thread_scan_result_done__unpack
                     (size_t               len,
                      const uint8_t       *data,
                      ThreadScanResultDone         *message)
{
  return (ThreadScanResultDone *)
     protobuf_c_message_unpack (&thread_scan_result_done__descriptor,
                                len, data, (ProtobufCMessage*)message);
}
void   thread_control__init
                     (ThreadControl         *message)
{
  static ThreadControl init_value = THREAD_CONTROL__INIT;
  *message = init_value;
}
size_t thread_control__pack
                     (const ThreadControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &thread_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
ThreadControl *
       thread_control__unpack
                     (size_t               len,
                      const uint8_t       *data,
                      ThreadControl         *message)
{
  return (ThreadControl *)
     protobuf_c_message_unpack (&thread_control__descriptor,
                                len, data, (ProtobufCMessage*)message);
}
static const ProtobufCEnumValue thread_primitive__type__enum_values_by_number[12] =
{
  { "THREAD_KEY", "THREAD_PRIMITIVE__TYPE__THREAD_KEY", 1 },
  { "THREAD_KEY_SEQUENCE", "THREAD_PRIMITIVE__TYPE__THREAD_KEY_SEQUENCE", 2 },
  { "THREAD_MESH_LOCAL_PREFIX", "THREAD_PRIMITIVE__TYPE__THREAD_MESH_LOCAL_PREFIX", 3 },
  { "THREAD_MODE", "THREAD_PRIMITIVE__TYPE__THREAD_MODE", 4 },
  { "THREAD_STATUS", "THREAD_PRIMITIVE__TYPE__THREAD_STATUS", 5 },
  { "THREAD_TIMEOUT", "THREAD_PRIMITIVE__TYPE__THREAD_TIMEOUT", 6 },
  { "IEEE802154_CHANNEL", "THREAD_PRIMITIVE__TYPE__IEEE802154_CHANNEL", 7 },
  { "IEEE802154_PANID", "THREAD_PRIMITIVE__TYPE__IEEE802154_PANID", 8 },
  { "IEEE802154_EXTENDED_PANID", "THREAD_PRIMITIVE__TYPE__IEEE802154_EXTENDED_PANID", 9 },
  { "IEEE802154_NETWORK_NAME", "THREAD_PRIMITIVE__TYPE__IEEE802154_NETWORK_NAME", 10 },
  { "IEEE802154_SHORT_ADDR", "THREAD_PRIMITIVE__TYPE__IEEE802154_SHORT_ADDR", 11 },
  { "IEEE802154_EXT_ADDR", "THREAD_PRIMITIVE__TYPE__IEEE802154_EXT_ADDR", 12 },
};
static const ProtobufCIntRange thread_primitive__type__value_ranges[] = {
{1, 0},{0, 12}
};
static const ProtobufCEnumValueIndex thread_primitive__type__enum_values_by_name[12] =
{
  { "IEEE802154_CHANNEL", 6 },
  { "IEEE802154_EXTENDED_PANID", 8 },
  { "IEEE802154_EXT_ADDR", 11 },
  { "IEEE802154_NETWORK_NAME", 9 },
  { "IEEE802154_PANID", 7 },
  { "IEEE802154_SHORT_ADDR", 10 },
  { "THREAD_KEY", 0 },
  { "THREAD_KEY_SEQUENCE", 1 },
  { "THREAD_MESH_LOCAL_PREFIX", 2 },
  { "THREAD_MODE", 3 },
  { "THREAD_STATUS", 4 },
  { "THREAD_TIMEOUT", 5 },
};
const ProtobufCEnumDescriptor thread_primitive__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ThreadPrimitive.Type",
  "Type",
  "ThreadPrimitive__Type",
  "",
  12,
  thread_primitive__type__enum_values_by_number,
  12,
  thread_primitive__type__enum_values_by_name,
  1,
  thread_primitive__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor thread_primitive__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ThreadPrimitive, type),
    &thread_primitive__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "bool",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ThreadPrimitive, value_case),
    offsetof(ThreadPrimitive, bool_),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "uint32",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ThreadPrimitive, value_case),
    offsetof(ThreadPrimitive, uint32),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "bytes",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ThreadPrimitive, value_case),
    offsetof(ThreadPrimitive, bytes),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    16,  /* max length */
  },
};
static const unsigned thread_primitive__field_indices_by_name[] = {
  1,   /* field[1] = bool */
  3,   /* field[3] = bytes */
  0,   /* field[0] = type */
  2,   /* field[2] = uint32 */
};
static const ProtobufCIntRange thread_primitive__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor thread_primitive__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadPrimitive",
  "ThreadPrimitive",
  "ThreadPrimitive",
  "",
  sizeof(ThreadPrimitive),
  4,
  thread_primitive__field_descriptors,
  thread_primitive__field_indices_by_name,
  1,  thread_primitive__number_ranges,
  (ProtobufCMessageInit) thread_primitive__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue thread_state__state__enum_values_by_number[4] =
{
  { "DETACHED", "THREAD_STATE__STATE__DETACHED", 0 },
  { "CHILD", "THREAD_STATE__STATE__CHILD", 1 },
  { "ROUTER", "THREAD_STATE__STATE__ROUTER", 2 },
  { "LEADER", "THREAD_STATE__STATE__LEADER", 3 },
};
static const ProtobufCIntRange thread_state__state__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex thread_state__state__enum_values_by_name[4] =
{
  { "CHILD", 1 },
  { "DETACHED", 0 },
  { "LEADER", 3 },
  { "ROUTER", 2 },
};
const ProtobufCEnumDescriptor thread_state__state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ThreadState.State",
  "State",
  "ThreadState__State",
  "",
  4,
  thread_state__state__enum_values_by_number,
  4,
  thread_state__state__enum_values_by_name,
  1,
  thread_state__state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor thread_state__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ThreadState, has_state),
    offsetof(ThreadState, state),
    &thread_state__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
};
static const unsigned thread_state__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange thread_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor thread_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadState",
  "ThreadState",
  "ThreadState",
  "",
  sizeof(ThreadState),
  1,
  thread_state__field_descriptors,
  thread_state__field_indices_by_name,
  1,  thread_state__number_ranges,
  (ProtobufCMessageInit) thread_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue thread_whitelist__type__enum_values_by_number[5] =
{
  { "STATUS", "THREAD_WHITELIST__TYPE__STATUS", 0 },
  { "LIST", "THREAD_WHITELIST__TYPE__LIST", 1 },
  { "ADD", "THREAD_WHITELIST__TYPE__ADD", 2 },
  { "DELETE", "THREAD_WHITELIST__TYPE__DELETE", 3 },
  { "CLEAR", "THREAD_WHITELIST__TYPE__CLEAR", 4 },
};
static const ProtobufCIntRange thread_whitelist__type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex thread_whitelist__type__enum_values_by_name[5] =
{
  { "ADD", 2 },
  { "CLEAR", 4 },
  { "DELETE", 3 },
  { "LIST", 1 },
  { "STATUS", 0 },
};
const ProtobufCEnumDescriptor thread_whitelist__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ThreadWhitelist.Type",
  "Type",
  "ThreadWhitelist__Type",
  "",
  5,
  thread_whitelist__type__enum_values_by_number,
  5,
  thread_whitelist__type__enum_values_by_name,
  1,
  thread_whitelist__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue thread_whitelist__status__enum_values_by_number[2] =
{
  { "DISABLE", "THREAD_WHITELIST__STATUS__DISABLE", 0 },
  { "ENABLE", "THREAD_WHITELIST__STATUS__ENABLE", 1 },
};
static const ProtobufCIntRange thread_whitelist__status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex thread_whitelist__status__enum_values_by_name[2] =
{
  { "DISABLE", 0 },
  { "ENABLE", 1 },
};
const ProtobufCEnumDescriptor thread_whitelist__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ThreadWhitelist.Status",
  "Status",
  "ThreadWhitelist__Status",
  "",
  2,
  thread_whitelist__status__enum_values_by_number,
  2,
  thread_whitelist__status__enum_values_by_name,
  1,
  thread_whitelist__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor thread_whitelist__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ThreadWhitelist, type),
    &thread_whitelist__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ThreadWhitelist, has_status),
    offsetof(ThreadWhitelist, status),
    &thread_whitelist__status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "address",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ThreadWhitelist, n_address),
    offsetof(ThreadWhitelist, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    sizeof(((ThreadWhitelist *)0)->address[0]),  /* elt_size */
    8,  /* max repeat */
    8,  /* max length */
  },
};
static const unsigned thread_whitelist__field_indices_by_name[] = {
  2,   /* field[2] = address */
  1,   /* field[1] = status */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange thread_whitelist__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor thread_whitelist__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadWhitelist",
  "ThreadWhitelist",
  "ThreadWhitelist",
  "",
  sizeof(ThreadWhitelist),
  3,
  thread_whitelist__field_descriptors,
  thread_whitelist__field_indices_by_name,
  1,  thread_whitelist__number_ranges,
  (ProtobufCMessageInit) thread_whitelist__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_ip6_addresses__field_descriptors[1] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ThreadIp6Addresses, n_address),
    offsetof(ThreadIp6Addresses, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    sizeof(((ThreadIp6Addresses *)0)->address[0]),  /* elt_size */
    4,  /* max repeat */
    16,  /* max length */
  },
};
static const unsigned thread_ip6_addresses__field_indices_by_name[] = {
  0,   /* field[0] = address */
};
static const ProtobufCIntRange thread_ip6_addresses__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor thread_ip6_addresses__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadIp6Addresses",
  "ThreadIp6Addresses",
  "ThreadIp6Addresses",
  "",
  sizeof(ThreadIp6Addresses),
  1,
  thread_ip6_addresses__field_descriptors,
  thread_ip6_addresses__field_indices_by_name,
  1,  thread_ip6_addresses__number_ranges,
  (ProtobufCMessageInit) thread_ip6_addresses__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_scan_request__field_descriptors[2] =
{
  {
    "channel_mask",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ThreadScanRequest, has_channel_mask),
    offsetof(ThreadScanRequest, channel_mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "scan_interval_per_channel",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ThreadScanRequest, has_scan_interval_per_channel),
    offsetof(ThreadScanRequest, scan_interval_per_channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
};
static const unsigned thread_scan_request__field_indices_by_name[] = {
  0,   /* field[0] = channel_mask */
  1,   /* field[1] = scan_interval_per_channel */
};
static const ProtobufCIntRange thread_scan_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor thread_scan_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadScanRequest",
  "ThreadScanRequest",
  "ThreadScanRequest",
  "",
  sizeof(ThreadScanRequest),
  2,
  thread_scan_request__field_descriptors,
  thread_scan_request__field_indices_by_name,
  1,  thread_scan_request__number_ranges,
  (ProtobufCMessageInit) thread_scan_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_scan_result__field_descriptors[6] =
{
  {
    "network_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, network_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    16,  /* max length */
  },
  {
    "ext_panid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, ext_panid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    8,  /* max length */
  },
  {
    "ext_addr",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, ext_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    8,  /* max length */
  },
  {
    "panid",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, panid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "channel",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, channel),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "rssi",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ThreadScanResult, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
};
static const unsigned thread_scan_result__field_indices_by_name[] = {
  4,   /* field[4] = channel */
  2,   /* field[2] = ext_addr */
  1,   /* field[1] = ext_panid */
  0,   /* field[0] = network_name */
  3,   /* field[3] = panid */
  5,   /* field[5] = rssi */
};
static const ProtobufCIntRange thread_scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor thread_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadScanResult",
  "ThreadScanResult",
  "ThreadScanResult",
  "",
  sizeof(ThreadScanResult),
  6,
  thread_scan_result__field_descriptors,
  thread_scan_result__field_indices_by_name,
  1,  thread_scan_result__number_ranges,
  (ProtobufCMessageInit) thread_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define thread_scan_result_done__field_descriptors NULL
#define thread_scan_result_done__field_indices_by_name NULL
#define thread_scan_result_done__number_ranges NULL
const ProtobufCMessageDescriptor thread_scan_result_done__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadScanResultDone",
  "ThreadScanResultDone",
  "ThreadScanResultDone",
  "",
  sizeof(ThreadScanResultDone),
  0,
  thread_scan_result_done__field_descriptors,
  thread_scan_result_done__field_indices_by_name,
  0,  thread_scan_result_done__number_ranges,
  (ProtobufCMessageInit) thread_scan_result_done__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_control__field_descriptors[7] =
{
  {
    "primitive",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ThreadControl, message_case),
    offsetof(ThreadControl, primitive),
    &thread_primitive__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ThreadControl, message_case),
    offsetof(ThreadControl, state),
    &thread_state__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "addresses",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ThreadControl, message_case),
    offsetof(ThreadControl, addresses),
    &thread_ip6_addresses__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "whitelist",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ThreadControl, message_case),
    offsetof(ThreadControl, whitelist),
    &thread_whitelist__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "scan_request",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ThreadControl, message_case),
    offsetof(ThreadControl, scan_request),
    &thread_scan_request__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "scan_result",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ThreadControl, message_case),
    offsetof(ThreadControl, scan_result),
    &thread_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
  {
    "scan_result_done",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ThreadControl, message_case),
    offsetof(ThreadControl, scan_result_done),
    &thread_scan_result_done__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL,   /* reserved1,reserved2, etc */
    0,  /* elt_size */
    0,  /* max repeat */
    0,  /* max length */
  },
};
static const unsigned thread_control__field_indices_by_name[] = {
  2,   /* field[2] = addresses */
  0,   /* field[0] = primitive */
  4,   /* field[4] = scan_request */
  5,   /* field[5] = scan_result */
  6,   /* field[6] = scan_result_done */
  1,   /* field[1] = state */
  3,   /* field[3] = whitelist */
};
static const ProtobufCIntRange thread_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor thread_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ThreadControl",
  "ThreadControl",
  "ThreadControl",
  "",
  sizeof(ThreadControl),
  7,
  thread_control__field_descriptors,
  thread_control__field_indices_by_name,
  1,  thread_control__number_ranges,
  (ProtobufCMessageInit) thread_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
